spring:
  datasource:
    url: jdbc:mysql://localhost:3306/documents
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB

logging.level:
  org.hibernate.SQL: debug


